name: Coverage

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  llvm-cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: Swatinem/rust-cache@v2
      - name: Generate coverage
        run: cargo llvm-cov --workspace --all-features --lcov --output-path lcov.info
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: lcov.info
          path: lcov.info
